Introduce the missions Blockade and Holy Raid
FAForever/faf-coop-maps pull request #367
Opened 2022-03-13 09:59 UTC by Garanas

Introduces the missions `Operation Blockade` and `Operation Holy Raid` made and maintained by Shadowlorda1. The missions have been thoroughly tested on the [Co-op development Discord server](https://discord.gg/ayzAVr9JUV). The quick tests that I've done myself also didn't show any errors.

2022-03-13 11:18 UTC, speed2CZ requested changes

2022-03-13 11:18 UTC, speed2CZ commented on FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_scenario.lua
> +    script = '/maps/FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua',
missing `map_version`

2022-03-13 11:18 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_scenario.lua
> +    script = '/maps/FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua',
missing `map_version`

2022-03-13 11:18 UTC, speed2CZ commented on FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_scenario.lua
> +    description = '',
no description?

2022-05-06 16:43 UTC, Garanas commented
Added / updated the missions from Discord. @speed2CZ can you review it again?

2022-05-08 11:23 UTC, speed2CZ requested changes
I left some notes

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +
empty else

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    buffDef = Buffs['CheatIncome']
copy pasta

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    buffAffects = buffDef.Affects
copy pasta

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    local AeonNuke = ArmyBrains[Order1]:GetListOfUnits(categories.uab2305, false)
again better to grab it by the name `ScenarioInfo.UnitNames[Order1]['Custom_Name']`

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    local AeonNuke2 = ArmyBrains[Order2]:GetListOfUnits(categories.uab2305, false)
again better to grab it by the name `ScenarioInfo.UnitNames[Order1]['Custom_Name']`

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    IssueNuke({AeonNuke[1]}, ScenarioUtils.MarkerToPosition('Nuke2'))
are you sure the nuke can't die while all these waiting, since that would then throw an error

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Holy Raid/FAF_Coop_Operation_Holy Raid_script.lua
> +    if ScenarioInfo.MissionNumber == 3 then
`~= 2` you only need to be checking for the number you intend to go from, since that should be the only correct one

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Ioz_Shavoh_Kael/FAF_Coop_Operation_Ioz_Shavoh_Kael_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Rescue/FAF_Coop_Operation_Rescue_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Tha_Atha_Aez/FAF_Coop_Operation_Tha_Atha_Aez_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Trident/FAF_Coop_Operation_Trident_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Uhthe_Thuum_QAI/FAF_Coop_Operation_Uhthe_Thuum_QAI_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Yath_Aez/FAF_Coop_Operation_Yath_Aez_scenario.lua
> -    map_version = 1,
no need to change this, its done by the deployment script

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Ioz_Shavoh_Kael/FAF_Coop_Operation_Ioz_Shavoh_Kael_script.lua
> +                if ( not result) then
empty callback

2022-05-08 11:23 UTC, speed2CZ commented on FAF_Coop_Operation_Tha_Atha_Aez/FAF_Coop_Operation_Tha_Atha_Aez_script.lua
> +    buffAffects.MassProduction.Mult = 2
copy pasta here again

2022-05-27 10:05 UTC, Garanas commented on FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua
> +    if ScenarioInfo.MissionNumber ~= 2 then
@speed2CZ are you sure that this is correct? 

The only place where the mission number is set to `2` is at line 270. Before that the mission number is going to be `1`. `1` does not equal `2`, so we end up with a return statement. Shouldn't this be `~= 1`, the value of the previous mission number?

2022-06-04 17:40 UTC, merged