Update Seraphim and Coalition maps
FAForever/faf-coop-maps pull request #417
Opened 2023-08-31 07:25 UTC by Garanas

Includes two new coalition maps:

- Red Revenge
- Rebel's Rest

And one new Seraphim map:

- Overlord Surth Velsok

2023-08-31 09:14 UTC, speed2CZ requested changes
- scenarios are missing `map_version` the server needs it to update the map correctly
- building from mobile factories has to be updated

2023-08-31 09:14 UTC, speed2CZ commented on FAF_Coop_Operation_Ioz_Shavoh_Kael/UEFaiP3.lua
> +local CustomFunctions = import('/maps/FAF_Coop_Operation_Thisl_Eniz/FAF_Coop_Operation_Thisl_Eniz_CustomFunctions.lua')
This line has to be deleted

2023-08-31 09:14 UTC, speed2CZ commented on FAF_Coop_Operation_Golden_Crystals/FAF_Coop_Operation_Golden_Crystals_scenario.lua
> -            factions = { {'uef', 'aeon', 'cybran'}, {'uef', 'aeon', 'cybran'}, {'uef', 'aeon', 'cybran'}, {'uef', 'aeon', 'cybran'} },
Not sure if this is intentional?

2023-08-31 09:14 UTC, speed2CZ commented on FAF_Coop_Operation_Rebel's_Rest/FAF_Coop_Operation_Rebel's_Rest_scenario.lua
> +        },
missing available factions?

2023-08-31 09:14 UTC, speed2CZ commented on FAF_Coop_Operation_Red_Revenge/FAF_Coop_Operation_Red_Revenge_scenario.lua
> +        },
missing available factions?

2023-10-02 07:44 UTC, speed2CZ approved these changes
Looks good

2024-02-27 06:45 UTC, zqh9843 commented
Overlord Surth Velsok had a weird lighting bug the last time I played. But it's not consistent on every platform tho. Seems to affect AMD CPU+NVIDIA GPU combination the most.

2024-02-27 09:47 UTC, Garanas commented
That can be tackled in a separate pull request.

2024-03-14 09:53 UTC, merged